name: ${name}
description: ${description}
author: Hadde
version: ${version}
main: de.eldoria.companies.Companies
api-version: 1.13
depend:
  - vault


commands:
  company:
    description: manage your company
    usage: Something
  order:
    description: create orders
