name: ${name}
description: ${description}
author: Hadde
version: ${version}
main: de.eldoria.companies.Companies
api-version: 1.13
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - ProtocolLib
libraries:
  - "com.zaxxer:HikariCP:5.0.0"
  - "org.mariadb.jdbc:mariadb-java-client:2.7.2"
  - "org.xerial:sqlite-jdbc:3.36.0.3"
  - "org.postgresql:postgresql:42.2.23"

commands:
  company:
    description: manage your company
    aliases:
      -
  order:
    description: create orders
  companyadmin:
    description: Manage the plugin

permissions:
  companies.*:
    description: gives access to all company commands
    children:
      companies.order.*: true
      companies.admin.*: true
      companies.company.*: true
  companies.order.*:
    description: gives full access to orders. Will not override the order limit
    children:
      companies.order.create: true
  companies.admin.*:
    description: gives access to admin commands
    children:
      companies.admin.level: true
  companies.company.*:
    description: gives access to company commands.
    children:
      companies.company.create: true

  companies.order.create:
    description: allows creation of orders
  companies.admin.level:
    description: allows managing of company level settings
  companies.company.create:
    description: allows creation of a company
